name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install talib
      run: |
        chmod +x install_talib.sh
        sudo ./install_talib.sh
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --extra-index-url $(cat extra-index-url) -e .[dev]
    - name: Code flake8 check
      run: |
        flake8
    - name: Test with pytest
      run: |
        pytest
